mod address;
mod area;
mod education;
mod email;
mod emoji;
mod file;
mod internet;
mod number;
mod person;
mod phone_number;
mod uuid;

pub use address::Address;
pub use education::Education;
pub use email::Email;
pub use emoji::Emoji;
pub use file::File;
pub use internet::Internet;
pub use number::Number;
pub use person::*;
pub use phone_number::PhoneNumber;
pub use uuid::Uuid;
